<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit9298c5a90206cec5318fee04e373024a
{
    public static $prefixLengthsPsr4 = array (
        'I' => 
        array (
            'Identicon\\' => 10,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Identicon\\' => 
        array (
            0 => __DIR__ . '/..' . '/yzalis/identicon/src/Identicon',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit9298c5a90206cec5318fee04e373024a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit9298c5a90206cec5318fee04e373024a::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
